/*************************************************************
 *
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  # 	#
 *	#		 # #			 #    #		# #				#
 *	 ###			#####    # #			###   #		  #				#
 *			 #   #		#					####
 *
 * Generated by tinyrpc framework tinyrpc_generator.py
 * This file will be overwrite every time
 * File Name: test_tinypb_server.h
 * Create Time: 2026-03-11 09:59:05
 * Allow Edit: False
 *************************************************************/

#ifndef TEST_TINYPB_SERVER_SERVICE_TEST_TINYPB_SERVER_H
#define TEST_TINYPB_SERVER_SERVICE_TEST_TINYPB_SERVER_H

#include <google/protobuf/service.h>
#include "test_tinypb_server/pb/test_tinypb_server.pb.h"

namespace test_tinypb_server {

class QueryServiceImpl : public QueryService {
   public:
    QueryServiceImpl() = default;

    ~QueryServiceImpl() = default;

    // override from QueryService
    virtual void query_name(::google::protobuf::RpcController* controller, const ::queryNameReq* request,
                            ::queryNameRes* response, ::google::protobuf::Closure* done);

    // override from QueryService
    virtual void query_age(::google::protobuf::RpcController* controller, const ::queryAgeReq* request,
                           ::queryAgeRes* response, ::google::protobuf::Closure* done);

   private:
    std::string name_;

    void init(std::string name);
};

}  // namespace test_tinypb_server

#endif