/*************************************************************
 *
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  # 	#
 *	#		 # #			 #    #		# #				#
 *	 ###			#####    # #			###   #		  #				#
 *			 #   #		#					####
 *
 * Generated by tinyrpc framework tinyrpc_generator.py
 * This file will be overwrite every time
 * File Name: test_tinypb_server.cc
 * Create Time: 2026-03-11 09:59:05
 * Allow Edit: False
 *************************************************************/

#include "test_tinypb_server/service/test_tinypb_server.h"
#include <google/protobuf/service.h>
#include <tinyrpc/comm/log.h>
#include <exception>
#include "test_tinypb_server/comm/business_exception.h"

#include "test_tinypb_server/pb/test_tinypb_server.pb.h"

namespace test_tinypb_server {

void QueryServiceImpl::init(std::string name) { name_ = name; }

void QueryServiceImpl::query_name(::google::protobuf::RpcController* controller, const ::queryNameReq* request,
                                  ::queryNameRes* response, ::google::protobuf::Closure* done) {
    init("Peter");
    response->set_ret_code(request->req_no());
    response->set_res_info(std::format("your req type = {}, and id = {}", request->type(), request->id()));
    response->set_id(666);
    response->set_name(name_);
}

void QueryServiceImpl::query_age(::google::protobuf::RpcController* controller, const ::queryAgeReq* request,
                                 ::queryAgeRes* response, ::google::protobuf::Closure* done) {}

}  // namespace test_tinypb_server