/*************************************************************
 *
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  # 	#
 *	#		 # #			 #    #		# #				#
 *	 ###			#####    # #			###   #		  #				#
 *			 #   #		#					####
 *
 * Generated by tinyrpc framework tinyrpc_generator.py
 * Create Time: 2026-03-07 11:36:32
 * This file will not be overwrite although protobuf file changed !!!
 * Just write this file while not exist
 * File Name: raft_rpc_service.cc
 * Create Time: 2026-03-07 11:36:32
 * Allow Edit: True
 *************************************************************/

#include <google/protobuf/service.h>
#include <tinyrpc/comm/start.h>
#include "raft_rpc_service/service/raft_rpc_service.h"

int main(int argc, char* argv[]) {
    if (argc != 2) {
        printf("Start raft_rpc_service server error, input argc is not 2!");
        printf("Start raft_rpc_service like this: \n");
        printf("./raft_rpc_service raft_rpc_service.xml\n");
        return 0;
    }

    tinyrpc::InitConfig(argv[1]);

    REGISTER_SERVICE(raft_rpc_service::raftRpcImpl);

    tinyrpc::StartRpcServer();

    return 0;
}