/*************************************************************
 *
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  # 	#
 *	#		 # #			 #    #		# #				#
 *	 ###			#####    # #			###   #		  #				#
 *			 #   #		#					####
 *
 * Generated by tinyrpc framework tinyrpc_generator.py
 * This file will not be overwrite although protobuf file changed !!!
 * Just write this file while not exist
 * File Name: test_query_name_client.cc
 * Create Time: 2026-03-11 09:59:05
 * Allow Edit: True
 *************************************************************/

#include <google/protobuf/service.h>
#include <tinyrpc/net/comm/net_address.h>
#include <tinyrpc/net/tinypb/tinypb_rpc_async_channel.h>
#include <tinyrpc/net/tinypb/tinypb_rpc_channel.h>
#include <tinyrpc/net/tinypb/tinypb_rpc_closure.h>
#include <tinyrpc/net/tinypb/tinypb_rpc_controller.h>
#include "test_tinypb_server/pb/test_tinypb_server.pb.h"

#include <tinyrpc/comm/log.h>
#include <tinyrpc/comm/start.h>
#include <tinyrpc/coroutine/coroutine.h>
#include <tinyrpc/coroutine/coroutine_pool.h>
#include <tinyrpc/net/tcp/tcp_server.h>

#include <atomic>
#include <chrono>
#include <thread>

static std::atomic<bool> g_running{true};

void test_client_loop() {
    tinyrpc::IPAddress::ptr addr = std::make_shared<tinyrpc::IPAddress>("127.0.0.1", 12345);

    while (g_running) {
        tinyrpc::TinyPbRpcChannel channel(addr);
        QueryService_Stub stub(&channel);
        tinyrpc::TinyPbRpcController rpc_controller;
        rpc_controller.SetTimeout(5000);

        ::queryNameReq rpc_req;
        ::queryNameRes rpc_res;
        rpc_req.set_req_no(2);
        rpc_req.set_id(2);
        rpc_req.set_type(2);

        stub.query_name(&rpc_controller, &rpc_req, &rpc_res, NULL);

        if (rpc_controller.ErrorCode() != 0) {
            std::cout << "Failed: " << rpc_controller.ErrorText() << std::endl;
        } else {
            std::cout << "Success: " << rpc_res.ShortDebugString() << std::endl;
        }

        // 间隔1秒再发下一个请求
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}

void test_client() {
    tinyrpc::IPAddress::ptr addr = std::make_shared<tinyrpc::IPAddress>("127.0.0.1", 12345);

    tinyrpc::TinyPbRpcChannel channel(addr);
    QueryService_Stub stub(&channel);

    tinyrpc::TinyPbRpcController rpc_controller;
    rpc_controller.SetTimeout(5000);

    ::queryNameReq rpc_req;
    ::queryNameRes rpc_res;

    rpc_req.set_req_no(2);
    rpc_req.set_id(2);
    rpc_req.set_type(2);

    std::cout << "Send to tinyrpc server " << addr->toString() << ", request body: [" << rpc_req.ShortDebugString()
              << "]" << std::endl;
    stub.query_name(&rpc_controller, &rpc_req, &rpc_res, NULL);

    if (rpc_controller.ErrorCode() != 0) {
        std::cout << "Failed to call tinyrpc server, error code: " << rpc_controller.ErrorCode()
                  << ", error info: " << rpc_controller.ErrorText() << std::endl;
        return;
    }

    std::cout << "Success get response from tinyrpc server " << addr->toString() << ", response body: ["
              << rpc_res.ShortDebugString() << "]" << std::endl;
}

int main(int argc, char* argv[]) {
    // test_client();
    std::thread t(&test_client_loop);

    // 主线程保持运行，按回车停止
    std::cout << "Press Enter to stop..." << std::endl;
    std::cin.get();

    g_running = false;
    t.join();  // 等待线程退出
    return 0;
}
