/*************************************************************
 *
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  # 	#
 *	#		 # #			 #    #		# #				#
 *	 ###			#####    # #			###   #		  #				#
 *			 #   #		#					####
 *
 * Generated by tinyrpc framework tinyrpc_generator.py
 * This file will not be overwrite althrough protobuf file changed !!!
 * Just write this file while not exist
 * File Name: test_append_entries_client.cc
 * Create Time: 2026-03-07 11:36:32
 * Allow Edit: True
 *************************************************************/

#include <google/protobuf/service.h>
#include <tinyrpc/net/comm/net_address.h>
#include <tinyrpc/net/tinypb/tinypb_rpc_async_channel.h>
#include <tinyrpc/net/tinypb/tinypb_rpc_channel.h>
#include <tinyrpc/net/tinypb/tinypb_rpc_closure.h>
#include <tinyrpc/net/tinypb/tinypb_rpc_controller.h>
#include "raft_rpc_service/pb/raft_rpc_service.pb.h"

void test_client() {
    tinyrpc::IPAddress::ptr addr = std::make_shared<tinyrpc::IPAddress>("127.0.0.1", 12345);

    tinyrpc::TinyPbRpcChannel channel(addr);
    raftRpc_Stub stub(&channel);

    tinyrpc::TinyPbRpcController rpc_controller;
    rpc_controller.SetTimeout(5000);

    ::AppendEntriesRequest rpc_req;
    ::AppendEntriesResponse rpc_res;

    rpc_req.set_term(10086);
    rpc_req.set_leader_id(8848);
    LogEntry* entry = rpc_req.add_entries();
    entry->set_command("append logs");
    entry->set_log_term(3);
    entry->set_log_index(666);

    std::cout << "Send to tinyrpc server " << addr->toString() << ", request body: [" << rpc_req.ShortDebugString()
              << "]" << std::endl;
    stub.AppendEntries(&rpc_controller, &rpc_req, &rpc_res, NULL);

    if (rpc_controller.ErrorCode() != 0) {
        std::cout << "Failed to call tinyrpc server, error code: " << rpc_controller.ErrorCode()
                  << ", error info: " << rpc_controller.ErrorText() << std::endl;
        return;
    }

    std::cout << "Success get response from tinyrpc server " << addr->toString() << ", rpc_res.info: ["
              << rpc_res.info() << "]" << std::endl;

    std::cout << "Success get response from tinyrpc server " << addr->toString() << ", response body: ["
              << rpc_res.ShortDebugString() << "]" << std::endl;
}

int main(int argc, char* argv[]) {
    test_client();

    return 0;
}
