/*************************************************************
 *
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  # 	#
 *	#		 # #			 #    #		# #				#
 *	 ###			#####    # #			###   #		  #				#
 *			 #   #		#					####
 *
 * Generated by tinyrpc framework tinyrpc_generator.py
 * Create Time: 2026-03-07 11:36:32
 * This file will not be overwrite although protobuf file changed !!!
 * Just write this file while not exist
 * File Name: append_entries.cc
 * Create Time: 2026-03-07 11:36:32
 * Allow Edit: True
 *************************************************************/

#include "raft_rpc_service/interface/append_entries.h"
#include <tinyrpc/comm/log.h>
#include "raft_rpc_service/interface/interface.h"
#include "raft_rpc_service/pb/raft_rpc_service.pb.h"

namespace raft_rpc_service {

AppendEntriesInterface::AppendEntriesInterface(const ::AppendEntriesRequest& request, ::AppendEntriesResponse& response,
                                               const tinyrpc::TinyPbRpcController& controller)
    : Interface(controller), req_(request), res_(response) {
    run();
}

AppendEntriesInterface::~AppendEntriesInterface() {}

void AppendEntriesInterface::run() {
    //
    // Run your business at here
    // res_.set_ret_code(0);
    // res_.set_res_info("Success");
    //
    res_.set_success(true);
    res_.set_info(std::format("the size of entries is {}", req_.entries().size()));
}

}  // namespace raft_rpc_service