/*************************************************************
 * 
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  #	  	#		#		 #
 *    #			 #    #		# #				#				 ###			#####    #		
 *    #			###   #		  #				#				 #   #		#					####
 *
 * ***********************************************************
 * Generated by tinyrpc framework tinyrpc_generator.py
 * This file will not be overwrite although protobuf file changed !!!
 * File can't overwrite while exist
 * ***********************************************************
 * File Name: append_entries.h
 * Create Time: 2026-03-06 21:31:21
 * Allow Edit: True
*************************************************************/

#ifndef RAFT_RPC_SERVICE_INTERFACE_APPEND_ENTRIES_H
#define RAFT_RPC_SERVICE_INTERFACE_APPEND_ENTRIES_H 

#include "raft_rpc_service/pb/raft_rpc_service.pb.h"
#include "raft_rpc_service/interface/interface.h"


namespace raft_rpc_service {

/*
 * Rpc Interface Class
 * Alloc one object every time RPC call begin, and destroy this object while RPC call end
*/

class AppendEntriesInterface : public Interface {
 public:

  AppendEntriesInterface(const ::AppendEntriesRequest& request, ::AppendEntriesResponse& response, const tinyrpc::TinyPbRpcController& controller);

  ~AppendEntriesInterface();

  void run();

 private:
  const ::AppendEntriesRequest& req_;      // request object from client

  ::AppendEntriesResponse& res_;           // response object that reply to client

};


}


#endif