/*************************************************************
 * 
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  #	  	#		#		 #
 *    #			 #    #		# #				#				 ###			#####    #		
 *    #			###   #		  #				#				 #   #		#					####
 *
 * Generated by tinyrpc framework tinyrpc_generator.py
 * This file will not be overwrite although protobuf file changed !!!
 * Just write this file while not exist
 * File Name: raft_rpc_service.h
 * Create Time: 2026-03-07 11:36:32
 * Allow Edit: True
*************************************************************/


#include <tinyrpc/net/tinypb/tinypb_rpc_closure.h>
#include <tinyrpc/net/tinypb/tinypb_rpc_controller.h>
#include "raft_rpc_service/interface/interface.h"

namespace raft_rpc_service {


Interface::Interface(const tinyrpc::TinyPbRpcController& controller) 
  : m_controller(controller) {

}

Interface::~Interface() {

}

}