/*************************************************************
 * 
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  #	  	#		#		 #
 *    #			 #    #		# #				#				 ###			#####    #		
 *    #			###   #		  #				#				 #   #		#					####
 *
 * Generated by tinyrpc framework tinyrpc_generator.py
 * This file will not be overwrite although protobuf file changed !!!
 * Just write this file while not exist
 * File Name: raft_rpc_service.h
 * Create Time: 2026-03-06 21:31:21
 * Allow Edit: True
*************************************************************/

#ifndef RAFT_RPC_SERVICE_INTERFACE_INTERFACE_H
#define RAFT_RPC_SERVICE_INTERFACE_INTERFACE_H 

#include <tinyrpc/net/tinypb/tinypb_rpc_closure.h>
#include <tinyrpc/net/tinypb/tinypb_rpc_controller.h>
#include <google/protobuf/message.h>

namespace raft_rpc_service {

/*
 * Rpc Interface Base Class
 * All interface should extend this abstract class
*/

class Interface {
 public:
  Interface(const tinyrpc::TinyPbRpcController& controller);

  virtual ~Interface();

  virtual void run() = 0;
 
 protected:
  const tinyrpc::TinyPbRpcController& m_controller;

};


}


#endif