/*************************************************************
 * 
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  #	  	#		#		 #
 *    #			 #    #		# #				#				 ###			#####    #		
 *    #			###   #		  #				#				 #   #		#					####
 *
 * Generated by tinyrpc framework tinyrpc_generator.py
 * Create Time: 2026-03-07 11:36:32
 * This file will not be overwrite although protobuf file changed !!!
 * Just write this file while not exist
 * File Name: request_vote.cc
 * Create Time: 2026-03-07 11:36:32
 * Allow Edit: True
*************************************************************/


#include <tinyrpc/comm/log.h>
#include "raft_rpc_service/interface/request_vote.h"
#include "raft_rpc_service/interface/interface.h"
#include "raft_rpc_service/pb/raft_rpc_service.pb.h"

namespace raft_rpc_service {

RequestVoteInterface::RequestVoteInterface(const ::RequestVoteRequest& request, ::RequestVoteReply& response, const tinyrpc::TinyPbRpcController& controller)
  : Interface(controller), 
  req_(request), 
  res_(response) {

}

RequestVoteInterface::~RequestVoteInterface() {

}

void RequestVoteInterface::run() {
  //
  // Run your business at here
  // res_.set_ret_code(0);
  // res_.set_res_info("Success");
  //

}


}