/*************************************************************
 * 
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  #	  	#		#		 #
 *    #			 #    #		# #				#				 ###			#####    #		
 *    #			###   #		  #				#				 #   #		#					####
 *
 * ***********************************************************
 * Generated by tinyrpc framework tinyrpc_generator.py
 * This file will not be overwrite although protobuf file changed !!!
 * File can't overwrite while exist
 * ***********************************************************
 * File Name: request_vote.h
 * Create Time: 2026-03-07 11:36:32
 * Allow Edit: True
*************************************************************/

#ifndef RAFT_RPC_SERVICE_INTERFACE_REQUEST_VOTE_H
#define RAFT_RPC_SERVICE_INTERFACE_REQUEST_VOTE_H 

#include "raft_rpc_service/pb/raft_rpc_service.pb.h"
#include "raft_rpc_service/interface/interface.h"


namespace raft_rpc_service {

/*
 * Rpc Interface Class
 * Alloc one object every time RPC call begin, and destroy this object while RPC call end
*/

class RequestVoteInterface : public Interface {
 public:

  RequestVoteInterface(const ::RequestVoteRequest& request, ::RequestVoteReply& response, const tinyrpc::TinyPbRpcController& controller);

  ~RequestVoteInterface();

  void run();

 private:
  const ::RequestVoteRequest& req_;      // request object from client

  ::RequestVoteReply& res_;           // response object that reply to client

};


}


#endif