/*************************************************************
 *
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  # 	#
 *	#		 # #			 #    #		# #				#
 *	 ###			#####    # #			###   #		  #				#
 *			 #   #		#					####
 *
 * Generated by tinyrpc framework tinyrpc_generator.py
 * This file will be overwrite every time
 * File Name: raft_rpc_service.cc
 * Create Time: 2026-03-07 11:36:32
 * Allow Edit: False
 *************************************************************/

#include "raft_rpc_service/service/raft_rpc_service.h"
#include <google/protobuf/service.h>
#include <tinyrpc/comm/log.h>
#include <exception>
#include "raft_rpc_service/comm/business_exception.h"
#include "raft_rpc_service/interface/append_entries.h"
#include "raft_rpc_service/interface/request_vote.h"
#include "raft_rpc_service/pb/raft_rpc_service.pb.h"

#include "raft_rpc_service/interface/interface.h"

namespace raft_rpc_service {

void raftRpcImpl::init(std::string str) { time_str = str; }

void raftRpcImpl::AppendEntries(::google::protobuf::RpcController* controller, const ::AppendEntriesRequest* request,
                                ::AppendEntriesResponse* response, ::google::protobuf::Closure* done) {
    // CALL_RPC_INTERFACE(AppendEntriesInterface);
    init("abcd");
    response->set_success("true");
    response->set_info(std::format("skip the call_rpc_interface, the size of entries is {}, and the time_str is {}",
                                   request->entries().size(), time_str));
}

void raftRpcImpl::RequestVote(::google::protobuf::RpcController* controller, const ::RequestVoteRequest* request,
                              ::RequestVoteReply* response, ::google::protobuf::Closure* done) {
    // CALL_RPC_INTERFACE(RequestVoteInterface);
}

}  // namespace raft_rpc_service