/*************************************************************
 * 
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  #	  	#		#		 #
 *    #			 #    #		# #				#				 ###			#####    #		
 *    #			###   #		  #				#				 #   #		#					####
 *
 * Generated by tinyrpc framework tinyrpc_generator.py
 * This file will be overwrite every time
 * File Name: raft_rpc_service.h
 * Create Time: 2026-03-07 11:36:32
 * Allow Edit: False 
*************************************************************/


#ifndef RAFT_RPC_SERVICE_SERVICE_RAFT_RPC_SERVICE_H 
#define RAFT_RPC_SERVICE_SERVICE_RAFT_RPC_SERVICE_H

#include <google/protobuf/service.h>
#include "raft_rpc_service/pb/raft_rpc_service.pb.h"

namespace raft_rpc_service {

class raftRpcImpl : public raftRpc {

 public:

  raftRpcImpl() = default;

  ~raftRpcImpl() = default;

  // override from raftRpc
  virtual void AppendEntries(::google::protobuf::RpcController* controller,
                       const ::AppendEntriesRequest* request,
                       ::AppendEntriesResponse* response,
                       ::google::protobuf::Closure* done);

  // override from raftRpc
  virtual void RequestVote(::google::protobuf::RpcController* controller,
                       const ::RequestVoteRequest* request,
                       ::RequestVoteReply* response,
                       ::google::protobuf::Closure* done);

  

};

}


#endif