/*************************************************************
 *
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  # 	#
 *	#		 # #			 #    #		# #				#
 *	 ###			#####    # #			###   #		  #				#
 *			 #   #		#					####
 *
 * Generated by tinyrpc framework tinyrpc_generator.py
 * This file will be overwrite every time
 * File Name: raft_rpc_service.cc
 * Create Time: 2026-03-06 21:31:21
 * Allow Edit: False
 *************************************************************/

#include "raft_rpc_service/service/raft_rpc_service.h"
#include <google/protobuf/service.h>
#include <tinyrpc/comm/log.h>
#include <exception>
#include "raft_rpc_service/comm/business_exception.h"
#include "raft_rpc_service/interface/append_entries.h"
#include "raft_rpc_service/pb/raft_rpc_service.pb.h"

#include "raft_rpc_service/interface/interface.h"

#define CALL_RPC_INTERFACE(type)                                                                                  \
    tinyrpc::TinyPbRpcController* con = dynamic_cast<tinyrpc::TinyPbRpcController*>(controller);                  \
    std::shared_ptr<type> impl = std::make_shared<type>(*request, *response, *con);                               \
    try {                                                                                                         \
        AppInfoLog(std::format("In|request:{}", request->ShortDebugString()));                                    \
        impl->run();                                                                                              \
        response->set_success(true);                                                                              \
        AppInfoLog(std::format("Out|response:{}", response->ShortDebugString()));                                 \
    } catch (raft_rpc_service::BusinessException & e) {                                                           \
        AppErrorLog(std::format("[{}:{}] occur BusinessException, error code={}, error info = {}", e.file_name(), \
                                e.line(), e.code(), e.error()));                                                  \
        response->set_success(false);                                                                             \
        response->set_info(e.error());                                                                            \
        AppErrorLog(std::format("Out|response:{}", response->ShortDebugString()));                                \
    } catch (std::exception&) {                                                                                   \
        AppErrorLog("occur std::exception, error code = -1, error_info = UnKnown error");                         \
        response->set_success(false);                                                                             \
        response->set_info("UnKnown error");                                                                      \
        AppErrorLog(std::format("Out|response:{}", response->ShortDebugString()));                                \
    } catch (...) {                                                                                               \
        AppErrorLog("occur UnKnown exception, error code = -1, error_info = UnKnown error");                      \
        response->set_success(false);                                                                             \
        response->set_info("UnKnown error");                                                                      \
        AppErrorLog(std::format("Out|response:{}", response->ShortDebugString()));                                \
    }                                                                                                             \
    if (done) {                                                                                                   \
        done->Run();                                                                                              \
    }

namespace raft_rpc_service {

void raftRpcImpl::AppendEntries(::google::protobuf::RpcController* controller, const ::AppendEntriesRequest* request,
                                ::AppendEntriesResponse* response, ::google::protobuf::Closure* done) {
    CALL_RPC_INTERFACE(AppendEntriesInterface);
}

}  // namespace raft_rpc_service