/*************************************************************
 * 
 *  #####   ###   #     #    #		 #     #####    #####     ####
 *    #			 #    #	#	  #			#		#			 #  #	  	#		#		 #
 *    #			 #    #		# #				#				 ###			#####    #		
 *    #			###   #		  #				#				 #   #		#					####
 *
 * Generated by tinyrpc framework tinyrpc_generator.py
 * Create Time: 2026-03-11 09:59:05
 * This file will not be overwrite although protobuf file changed !!!
 * Just write this file while not exist
 * File Name: test_tinypb_server.cc
 * Create Time: 2026-03-11 09:59:05
 * Allow Edit: True
*************************************************************/


#include <google/protobuf/service.h>
#include <tinyrpc/comm/start.h>
#include "test_tinypb_server/service/test_tinypb_server.h"

int main(int argc, char* argv[]) {
  if (argc != 2) {
    printf("Start test_tinypb_server server error, input argc is not 2!");
    printf("Start test_tinypb_server like this: \n");
    printf("./test_tinypb_server test_tinypb_server.xml\n");
    return 0;
  }

  tinyrpc::InitConfig(argv[1]);

  REGISTER_SERVICE(test_tinypb_server::QueryServiceImpl);

  tinyrpc::StartRpcServer();
  
  return 0;
}